# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

Udemy Course
"""

import pandas as pd

df = pd.read_csv('/content/file (4).csv')

df.head()

"""Q. 1) What are all different subjects for which Udemy is offering courses ?

"""

df['subject'].unique()

"""2) Which subject has the maximum number of courses."""

as_2 = df['subject'].max()
as_2

"""3) Show all the courses which are Free of Cost."""

as_3 = df[df['is_paid'] == False]
as_3

"""Q. 4) Show all the courses which are Paid."""

as_4 = df[df['is_paid'] == True]
as_4

"""Q. 5) Which are Top Selling Courses ?"""

as_5 = df.sort_values('num_subscribers', ascending = False)
as_5.head(5)

"""Q. 6) Which are Least Selling Courses ?"""

as_6 = df.sort_values('num_subscribers',ascending = True)
as_6.head(5)

"""Q. 7) Show all courses of Graphic Design where the price is below 100 ?"""

as_7 = df[(df['subject'] == 'Graphic Design')& (df['price'] < '100')  ]
as_7

"""Q. 8) List out all the courses that are related to 'Python'."""

as_8 = df[df['course_title'].str.contains("Python")]
as_8

"""Q. 9) What are courses that were published in the year 2015 ?"""

df.head(2)

as_9 = df[df['published_timestamp'].str.contains("2015")]
as_9

"""Q. 10) What is the Max. Number of Subscribers for Each Level of courses ?"""

df.groupby('level').num_subscribers.max()