# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

import pandas as pd

df = pd.read_csv("/content/file.csv")

df.describe()

"""Q. 1) Find all the unique 'Wind Speed' values in the data"""

wi_spe = df['Wind Speed_km/h'].unique()
wi_spe

"""Q. 2) Find the number of times when the 'Weather is exactly Clear'."""

clear_weather = df[df['Weather'] == 'Clear'].count()
clear_weather

"""Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'."""

as_3 = df[df['Wind Speed_km/h'] == 4].count()
as_3

"""Q. 4) Find out all the Null Values in the data."""

as_4 = df.isnull().sum()
as_4

"""Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'."""

df = df.rename(columns = {'Weather' : 'Weather_Condition'})
print(df)

"""Q. 6) What is the mean 'Visibility' ?"""

as_6 = df['Visibility_km'].mean()
print(as_6)

"""Q. 7) What is the Standard Deviation of 'Pressure' in this data?"""

as_7 = df['Press_kPa'].std()
print(as_7)

"""Q. 8) What is the Variance of 'Relative Humidity' in this data ?"""

as_8 = df['Rel Hum_%'].var()
print(as_8)

"""Q. 9) Find all instances when 'Snow' was recorded."""

as_9 = df[df['Weather_Condition'] == 'Snow']
as_9

"""Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'."""

as_10 = df[(df['Wind Speed_km/h'] >= 24) & (df['Visibility_km'] == 25) ]
print(as_10)

"""Q. 11) What is the Mean value of each column against each 'Weather Condition ?"""

as_11 = df.groupby('Weather_Condition').mean(numeric_only = True)
print(as_11)

"""Q. 12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?"""

as_12 = df.groupby('Weather_Condition').min(numeric_only = True)
print(as_12)
as_12_a = df.groupby('Weather_Condition').max(numeric_only = True)
print(as_12_a)

"""Q. 14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'."""

as_14 = df[(df['Weather_Condition'] == 'Clear') | (df['Visibility_km'] > 40)]
print(as_14)

